apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: registry.gitlab.com/nazarenko.serh/devops-example/master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com